name: Python 2

on: # [push]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Actions Checkout v4
        uses: actions/checkout@v4
        #with:
        #  base: main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          #  ['python-version', 'python-version-file', 'cache', 'architecture', 'check-latest', 'token', 
          #   'cache-dependency-path', 'update-environment', 'allow-prereleases', 'freethreaded']
          #dry_run: false <-- Warning: Unexpected input(s) 'dry_run'
      - name: python-2 multi-line
        shell: python
        run: |
          import os
          #print('os.environ["PATH"]:', os.environ['PATH'])
          print('Current Working Directory 1:', os.getcwd())
          import sys
          print('Python Version:', sys.version)
          with open("demofile", "a") as f:
              f.write("Now the file has more content!" + "\n")
              f.write("Apppending some more content." + "\n")
          print("os.listdir():", os.listdir())
          print("Contents of demofile:")
          with open("demofile", "r") as fin:
              for line in fin.readlines():
                  print(line)
          print("end")
          
# Current Working Directory 1: /home/runner/work/test.github.io/test.github.io
# Python Version: 3.13.3 (main, Apr  9 2025, 01:39:32) [GCC 13.3.0]
# os.listdir(): ['demofile', '.github', '.git', 'README.md']
# Contents of demofile:
# Now the file has more content!
#
# Apppending some more content.
#
# end

  
