name: Python 3
# Example from https://gitea.com/actions/checkout
# Push a commit using the built-in token
# Should create the file generated.txt

on: # [push]

  # Run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    permissions: write-all
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Actions Checkout v4
        uses: actions/checkout@v4
        #with:
        #  base: main TODO run in src
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          #  ['python-version', 'python-version-file', 'cache', 'architecture', 'check-latest', 'token', 
          #   'cache-dependency-path', 'update-environment', 'allow-prereleases', 'freethreaded']
          #dry_run: false <-- Warning: Unexpected input(s) 'dry_run'
      - name: Python-3 multi-line code
        shell: python
        run: |
          import os
          import sys
          import subprocess
          
          #date > generated.txt

          # Add a folder. like bash mkdir
          #mkdir -p test
          
          folder_list = ["testa", "testb", "testc",]          
          for folder in folder_list:
              os.makedirs(folder, exist_ok=True)

              # Add a file. Like touch in bash
              # Have a list, add files from list loop
              file_list = ["testfile", "testfile1", "testfile2",]
              for file in file_list:
                  if not os.path.exists(folder + "/" + file):
                      os.mknod(folder + "/" + file)
              
          #date > test/generated1.txt
          
          subprocess.run('''
              # Git instructions - performed by bash
              git config user.name "irsbugs"
              git config user.email "irsbugs@hotmail.com"          
              git add .
              git commit -m "generated"
              git push''',
              shell=True, check=True, executable='/bin/bash')
          
          #git config user.name "github-actions[bot]"
          #git config user.name "irsbugs"          
          #git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git config user.email "irsbugs@hotmail.com"          
          #git add .
          #git commit -m "generated"
          #git push
