name: Python 2

on: # [push]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: python-2 multi-line      
        run: |
          python -c "import sys; print('Python Version:', sys.version)"
          python -c "import os; print('Current Working Directory 1:', os.getcwd())"
          python -c "import os; print('Current Working Directory 2:', os.getcwd())" 
          
          
          # Fails Did you forget to import os? Needs to be all in one command
          #python - c "import os"
          #python -c "print('Current Working Directory 2:', os.getcwd())"
  
    #pip install --upgrade pip
    #pip install -r requirements.txt
    #
  
